# Generated by Django 5.2.10 on 2026-03-09 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hansviet_admin', '0003_package_patientprofile_progressnote_purchase_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to='news/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to='services/'),
        ),
    ]
