# Generated by Django 6.0.3 on 2026-03-10 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hansviet_admin', '0005_exerciselog_exerciseprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='ai_source',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='is_auto_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='needs_review',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='source_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='source_url',
            field=models.URLField(blank=True),
        ),
    ]
