# Generated by Django 6.0.1 on 2026-03-11 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hansviet_admin', '0007_newsarticle_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='expiry_reminder_3d_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
