# Generated by Django 6.0.1 on 2026-03-11 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hansviet_admin', '0008_purchase_expiry_reminder_3d_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='booking_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='booking_service',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='lead',
            name='booking_specialty',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
