# Generated by Django 6.0.1 on 2026-03-11 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hansviet_admin', '0009_lead_booking_date_lead_booking_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='booking_ack_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
