# Generated by Django 6.0.1 on 2026-03-11 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hansviet_admin', '0010_lead_booking_ack_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='expiry_reminder_days_sent',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
